model:
    arch: linknet3d_exp
data:
    dataset: sasha
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    mods: ['FLAIR','T1', 'FLAIR']
    macroblock_num_along_one_dim: 2
    path: "/media/machine/Storage/Dataset/BrainLesion/sashaSplit/train&val/"
training:
    train_iters: 300000
    patch_size: 96  #160 for unet3d #192 for linknet3d
    batch_size: 7
    val_interval: 20
    n_workers: 2
    cross_entropy_ratio: 0.003
    loss_balance_ratio: 1
    print_interval: 1
    print_interval_per_batch: False
    augmentations:
    optimizer:
        name: 'adam'
        lr: 0.03
        weight_decay: 0.0005
        #momentum: 0.99
    loss:
        name: 'cross_entropy3d'
        size_average: True
    lr_schedule:
    resume: unet_miccai2008AS_best_model.pkl
